version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    ports:
      - 3000
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=shop.theminingking.com
      - LETSENCRYPT_HOST=shop.theminingking.com
      - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
    volumes:
      - .:/home/node
      - /home/node/node_modules



#    links:
#      - mongo

  mongo:  
    image: mongo
    restart: unless-stopped
#    volumes_from:
#      - accountant_mongo_data
#    ports:
#      - "27017"
    command: --smallfiles #--rest --auth
    volumes:
      - crypto_cart_data:/data/db



#  mongo:
#    restart: unless-stopped
#    image: redis
#    command: redis-server --appendonly yes
#    volumes:
#      - corpus_data:/data


volumes:
  crypto_cart_data:

networks:
  default:
    external:
      name: nginx-proxy
